apiVersion: apps/v1

kind: Deployment

metadata:

  name: poi

spec:

  selector:

    matchLabels:

      run: poi

  replicas: 2

  template:

    metadata:

      labels:

        run: poi

    spec:

      containers:

       name: poi

       image: registryzwl7908.azurecr.io/tripinsights/poi:v2.0ar

        ports:

          containerPort: 80
