apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  selector:
    matchLabels:
      app: tripviewer
  replicas: 2
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryzwl7908.azurecr.io/tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://trips.api.svc.cluster.local"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile.api.svc.cluster.local"
---       
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web
spec:
  type: ClusterIP
  selector:
    app: tripviewer  
  ports:
  - port: 80
    targetPort: 80
  