apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: api
  name: trips
  labels:
    app: trips
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryzwl7908.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 80
        env: 
          - name: SQL_USER
            value: "sqladminzWl7908"
          - name: SQL_PASSWORD
            value: "yL5at0Tl6"
          - name: SQL_SERVER
            value: "sqlserverzwl7908.database.windows.net"
          - name:  SQL_DBNAME
            value: "mydrivingDB"
---
apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: trips
  labels:
    app: trips
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: trips
---