apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
  labels:
    app: trips
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryzwl7908.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: keyvault
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: keyvault
        flexVolume:
          driver: "azure/kv"
          options:
            keyvaultname: "WA8KSKeyVault"
            keyvaultobjectnames: "SQLUSER;SQLPASSWORD;SQLSERVER;SQLDBNAME"
            keyvaultobjecttypes: "secret;secret;secret;secret"
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER;SQL_DBNAME"
            resourcegroup: "teamResources"
            subscriptionid: "67db0cb5-d026-4e61-9c32-5d98c5df9058"
            tenantid: "ac3ae993-286f-431d-9c49-cfb474e9b77c"
            usevmmanagedidentity: "true"      
            vmmanagedidentityclientid: "c8ebe526-b662-48a3-ad60-cc6290e9aeed"  
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
  labels:
    app: trips
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: trips
---