apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-viewer
spec:
  selector:
    matchLabels:
      run: trip-viewer
  replicas: 2
  template:
    metadata:
      labels:
        run: trip-viewer
    spec:
      containers:
      - name: trip-viewer
        image: registryzwl7908.azurecr.io/tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://trips"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile"
        
apiVersion: v1
kind: Service
metadata:
  name: trip-viewer-web
spec:
  type: loadbalancer
  selector:
    app: trip-viewer  
  ports:
  - port: 80
  