apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: user-java
        image: registryzwl7908.azurecr.io/tripinsights/user-java:1.0
        ports:
        - containerPort: 80
          name: user-java
        volumeMounts:
        - name: keyvault
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: keyvault
        flexVolume:
          driver: "azure/kv"
          options:
            keyvaultname: "WA8KSKeyVault"
            keyvaultobjectnames: "SQLUSER;SQLPASSWORD;SQLSERVER;SQLDBNAME"
            keyvaultobjecttypes: "secret;secret;secret;secret"
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER;SQL_DBNAME"
            resourcegroup: "teamResources"
            subscriptionid: "67db0cb5-d026-4e61-9c32-5d98c5df9058"
            tenantid: "ac3ae993-286f-431d-9c49-cfb474e9b77c"
            usevmmanagedidentity: "true"      
            vmmanagedidentityclientid: "c8ebe526-b662-48a3-ad60-cc6290e9aeed"           
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: api
spec:
  ports:
  - port: 80
  selector:
    app: user-java
