apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: poi
        image: registryzwl7908.azurecr.io/tripinsights/user-java:1.0
        env: 
        - name: SQL_USER
          value: "sqladminzWl7908"
        - name: SQL_PASSWORD
          value: "yL5at0Tl6"
        - name: SQL_SERVER
          value: "sqlserverzwl7908.database.windows.net"
        - name:  SQL_DBNAME
          value: "mydrivingDB"
        ports:
        - containerPort: 80
          name: poi
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: tripviewer
spec:
  ports:
  - port: 80
  selector:
    app: user-java
