apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: poi
        image: registryzwl7908.azurecr.io/tripinsights/user-java:1.0
        envFrom:
        - secretRef:
            name: sql
        ports:
        - containerPort: 80
          name: poi
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: tripviewer
spec:
  ports:
  - port: 80
  selector:
    app: user-java
