apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
spec:
  selector:
    matchLabels:
      run: userprofile
  replicas: 3
  template:
    metadata:
      labels:
        run: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryzwl7908.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: keyvault
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: keyvault
        flexVolume:
          driver: "azure/kv"
          options:
            keyvaultname: "WA8KSKeyVault"
            keyvaultobjectnames: "SQLUSER;SQLPASSWORD;SQLSERVER;SQLDBNAME"
            keyvaultobjecttypes: "secret;secret;secret;secret"
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER;SQL_DBNAME"
            resourcegroup: "teamResources"
            subscriptionid: "67db0cb5-d026-4e61-9c32-5d98c5df9058"
            tenantid: "ac3ae993-286f-431d-9c49-cfb474e9b77c"
            usevmmanagedidentity: "true"      
            vmmanagedidentityclientid: "c8ebe526-b662-48a3-ad60-cc6290e9aeed"  
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: api
  labels:
    run: userprofile
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  selector:
    run: userprofile
