apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  selector:
    matchLabels:
      run: userprofile
  replicas: 3
  template:
    metadata:
      labels:
        run: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryzwl7908.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 80
