kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: web-edit-access-rolebinding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-edit-access
subjects:
- kind: User
  namespace: web
  name: "webdev@OTAPRD362ops.onmicrosoft.com"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: web-view-access-rolebinding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-view-access
subjects:
- kind: User
  namespace: web
  name: "apidev@OTAPRD362ops.onmicrosoft.com"